name: 'nyc_mta_ridership'
version: '1.0.0'

profile: 'nyc_mta_ridership'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_mta_ridership:
    +materialized: view
